{"name": "test_vwo_login_negative_tc4", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('setup', <FixtureRequest for <Function test_vwo_login_negative_tc4>>)", "trace": "file C:\\Python-Selenium\\Framework\\Automation_Framework2\\tests\\test\\vwoLoginTests\\prod\\test_vwo_login_pf.py, line 56\n      @pytest.mark.usefixtures(\"setup\")\n      @pytest.mark.qa\n      def test_vwo_login_negative_tc4(self, setup):\nE       fixture 'setup' not found\n>       available fixtures: _session_faker, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, extra, extras, faker, include_metadata_in_junit_xml, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, worker_id\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Python-Selenium\\Framework\\Automation_Framework2\\tests\\test\\vwoLoginTests\\prod\\test_vwo_login_pf.py:56"}, "start": 1741009204896, "stop": 1741009204896, "uuid": "bef0c022-25d5-49c5-a8eb-a463422b0e8a", "historyId": "f5c51936bfb82e8ab732ccc8f5e83974", "testCaseId": "f5c51936bfb82e8ab732ccc8f5e83974", "fullName": "tests.test.vwoLoginTests.prod.test_vwo_login_pf.TestVWOLogin#test_vwo_login_negative_tc4", "labels": [{"name": "epic", "value": "VWO App"}, {"name": "feature", "value": "Login Test"}, {"name": "tag", "value": "qa"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests.test.vwoLoginTests.prod"}, {"name": "suite", "value": "test_vwo_login_pf"}, {"name": "subSuite", "value": "TestVWOLogin"}, {"name": "host", "value": "DESKTOP-SJ9H8P2"}, {"name": "thread", "value": "2428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.vwoLoginTests.prod.test_vwo_login_pf"}]}